name: Docker Compose CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  compose:
    name: Validate Docker Compose setup
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Create default environment file
        run: cp .env.example .env

      - name: Validate docker-compose configuration
        run: docker compose -f docker-compose.yml config

      - name: Start services
        run: docker compose -f docker-compose.yml up -d --quiet-pull

      - name: Show running containers
        run: docker ps

      - name: Tear down services
        if: always()
        run: docker compose -f docker-compose.yml down
