name: Notion Sync

on:
  issues:
    types: [opened, edited, closed, reopened]
  pull_request:
    types: [opened, reopened, closed]
  discussions:
    types: [created, answered]
  projects_v2_item:
    types: [created, updated, deleted]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Notion Sync
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_PAGE_ID: ${{ secrets.NOTION_PAGE_ID }}
          NOTION_DISCUSSIONS_ARC_DB_ID: ${{ secrets.NOTION_DISCUSSIONS_ARC_DB_ID }}
          NOTION_ISSUES_BACKLOG_DB_ID: ${{ secrets.NOTION_ISSUES_BACKLOG_DB_ID }}
          NOTION_KNOWLEDGE_FILE_DB_ID: ${{ secrets.NOTION_KNOWLEDGE_FILE_DB_ID }}
          NOTION_PROJECT_BOARD_BACKLOG_DB_ID: ${{ secrets.NOTION_PROJECT_BOARD_BACKLOG_DB_ID }}
          NOTION_TASK_BACKLOG_DB_ID: ${{ secrets.NOTION_TASK_BACKLOG_DB_ID }}
          NOTION_PERFORMANCE_LOG_DB_ID: ${{ secrets.NOTION_PERFORMANCE_LOG_DB_ID }}
          AGENT_ACTIONS: ${{ secrets.AGENT_ACTIONS }}
        run: python scripts/notion_sync.py
