name: Wiki Sync

on:
  push:
    branches: [main]
    paths:
      - 'docs/**'

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout wiki
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}.wiki
          path: wiki
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Synchronize documentation
        run: |
          python scripts/wiki_sync.py --docs docs --wiki wiki

      - name: Commit and push wiki updates
        run: |
          cd wiki
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add .
            git commit -m "Sync documentation from main" || echo "No changes to commit"
            git push
          else
            echo "No wiki updates required"
          fi
